--- #YAML:1.0
name:               Business-PL-PESEL
version:            0.07
abstract:           Validate Polish Universal Electronic System for Registration 
author:
    - Tomasz Konojacki <xenu@poczta.onet.pl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Number::Range:  0
    Time::Piece:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
